use_default_settings: true

general:
  instance_name: "My SearXNG"

search:
  safe_search: 1
  autocomplete: "duckduckgo"
  default_lang: "en"

server:
  secret_key: "$SEARXNG_SECRET_KEY"
  bind_address: "127.0.0.1"
  port: 24652

ui:
  default_theme: simple

engines:
  - name: hister
    engine: json_engine
    shortcut: hi
    url: http://127.0.0.1:4433/search?q={query}
    results_query: documents
    url_query: url
    title_query: title
    content_query: text
    categories: [general]
    weight: 2
    timeout: 3.0

  - name: qwant
    engine: qwant
    shortcut: qw

  - name: google
    engine: google
    shortcut: go

  - name: bing
    engine: bing
    shortcut: bi

  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg

  - name: brave
    engine: brave
    shortcut: br

  - name: yahoo
    engine: yahoo
    shortcut: yh

  - name: startpage
    engine: startpage
    shortcut: sp

  - name: qwant
    engine: qwant
    shortcut: qw

  - name: mojeek
    engine: mojeek
    shortcut: mj

  - name: wikipedia
    engine: wikipedia
    shortcut: wp
